In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [38]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'
}
html_data = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers).text

In [42]:
soup = BeautifulSoup(html_data,'lxml')

In [46]:
company = soup.find_all('div', class_='companyCardWrapper')

In [47]:
len(company)

20

In [112]:
name = []
rating = []
reviews = []
jobs = []
industry = []
location = []
for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find(class_='rating_text').text.strip())
    reviews.append(i.find('a', class_='companyCardWrapper__ActionWrapper').text.strip())
    
    # Directly targets the anchor tag containing the jobs URL string
    jobs.append(i.find('a', href=lambda href: href and '-jobs-cmp' in href).text.strip())
    industry.append(i.find('span', class_='companyCardWrapper__interLinking').text.split('|')[0].strip())
    location.append(i.find('span', class_='companyCardWrapper__interLinking').text.split('|')[1].strip())

In [52]:
name

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'HCLTech',
 'ICICI Bank',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Axis Bank',
 'Jio',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTM Limited',
 'HDB Financial Services']

In [97]:
rating

['3.3',
 '3.7',
 '3.6',
 '3.7',
 '3.6',
 '3.8',
 '3.5',
 '3.4',
 '3.9',
 '3.3',
 '3.6',
 '3.9',
 '3.6',
 '4.4',
 '3.5',
 '3.9',
 '3.9',
 '4.6',
 '3.6',
 '3.9']

In [101]:
reviews

['1.2L Reviews',
 '75.4k Reviews',
 '66.6k Reviews',
 '62.9k Reviews',
 '55k Reviews',
 '54.1k Reviews',
 '50k Reviews',
 '47.2k Reviews',
 '46.8k Reviews',
 '44.4k Reviews',
 '43.6k Reviews',
 '39.8k Reviews',
 '34.2k Reviews',
 '34.1k Reviews',
 '33k Reviews',
 '32.5k Reviews',
 '27.9k Reviews',
 '27.6k Reviews',
 '27.2k Reviews',
 '26.4k Reviews']

In [ ]:
company[0]

In [109]:
jobs

['4.7k Jobs',
 '18.7k Jobs',
 '4.1k Jobs',
 '900 Jobs',
 '2k Jobs',
 '236 Jobs',
 '3k Jobs',
 '252 Jobs',
 '30 Jobs',
 '613 Jobs',
 '501 Jobs',
 '1.8k Jobs',
 '209 Jobs',
 '-- Jobs',
 '13 Jobs',
 '71 Jobs',
 '106 Jobs',
 '66 Jobs',
 '592 Jobs',
 '3 Jobs']

In [113]:
location

['Bengaluru +449 other locations',
 'Bengaluru +261 other locations',
 'Hyderabad +375 other locations',
 'Hyderabad +234 other locations',
 'Bengaluru +188 other locations',
 'Mumbai +1869 other locations',
 'Bengaluru +247 other locations',
 'Chennai +232 other locations',
 'Mumbai +1453 other locations',
 'Hyderabad +324 other locations',
 'Hyderabad +181 other locations',
 'Mumbai +259 other locations',
 'Mumbai +1537 other locations',
 'Mumbai +1967 other locations',
 'Bengaluru +185 other locations',
 'Bengaluru +520 other locations',
 'Mumbai +1169 other locations',
 'Noida +55 other locations',
 'Bengaluru +147 other locations',
 'Mumbai +1101 other locations']

In [111]:
industry

['IT Services & Consulting',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'Banking',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'Banking',
 'IT Services & Consulting',
 'Analytics & KPO',
 'BPO',
 'Banking',
 'Telecom',
 'BPO',
 'Internet',
 'Retail',
 'BPO',
 'IT Services & Consulting',
 'NBFC']

In [114]:
import pandas as pd

df = pd.DataFrame({
    'name': name,
    'rating': rating,
    'reviews': reviews,
    'jobs': jobs,
    'industry': industry,
    'location': location
})

In [115]:
df

,name,rating,reviews,jobs,industry,location
0,TCS,3.3,1.2L Reviews,4.7k Jobs,IT Services & Consulting,Bengaluru +449 other locations
1,Accenture,3.7,75.4k Reviews,18.7k Jobs,IT Services & Consulting,Bengaluru +261 other locations
2,Wipro,3.6,66.6k Reviews,4.1k Jobs,IT Services & Consulting,Hyderabad +375 other locations
3,Cognizant,3.7,62.9k Reviews,900 Jobs,IT Services & Consulting,Hyderabad +234 other locations
4,Capgemini,3.6,55k Reviews,2k Jobs,IT Services & Consulting,Bengaluru +188 other locations
5,HDFC Bank,3.8,54.1k Reviews,236 Jobs,Banking,Mumbai +1869 other locations
6,Infosys,3.5,50k Reviews,3k Jobs,IT Services & Consulting,Bengaluru +247 other locations
7,HCLTech,3.4,47.2k Reviews,252 Jobs,IT Services & Consulting,Chennai +232 other locations
8,ICICI Bank,3.9,46.8k Reviews,30 Jobs,Banking,Mumbai +1453 other locations
9,Tech Mahindra,3.3,44.4k Reviews,613 Jobs,IT Services & Consulting,Hyderabad +324 other locations
10,Genpact,3.6,43.6k Reviews,501 Jobs,Analytics & KPO,Hyderabad +181 other locations
11,TP,3.9,39.8k Reviews,1.8k Jobs,BPO,Mumbai +259 other locations
12,Axis Bank,3.6,34.2k Reviews,209 Jobs,Banking,Mumbai +1537 other locations
13,Jio,4.4,34.1k Reviews,-- Jobs,Telecom,Mumbai +1967 other locations
14,Concentrix Corporation,3.5,33k Reviews,13 Jobs,BPO,Bengaluru +185 other locations
15,Amazon,3.9,32.5k Reviews,71 Jobs,Internet,Bengaluru +520 other locations
16,Reliance Retail,3.9,27.9k Reviews,106 Jobs,Retail,Mumbai +1169 other locations
17,iEnergizer,4.6,27.6k Reviews,66 Jobs,BPO,Noida +55 other locations
18,LTM Limited,3.6,27.2k Reviews,592 Jobs,IT Services & Consulting,Bengaluru +147 other locations
19,HDB Financial Services,3.9,26.4k Reviews,3 Jobs,NBFC,Mumbai +1101 other locations

In [122]:

import time
import random
import requests
from bs4 import BeautifulSoup
import pandas as pd

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

session = requests.Session()
session.headers.update(HEADERS)

df_list = []
consecutive_empty = 0
MAX_CONSECUTIVE_EMPTY = 3   # stop early if we hit several blank/blocked pages in a row

for page in range(1, 500):
    url = f'https://www.ambitionbox.com/list-of-companies?page={page}'

    try:
        resp = session.get(url, timeout=15)
        resp.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"[page {page}] request failed: {e} — skipping")
        consecutive_empty += 1
        if consecutive_empty >= MAX_CONSECUTIVE_EMPTY:
            print("Too many consecutive failures, stopping.")
            break
        time.sleep(5)
        continue

    soup = BeautifulSoup(resp.text, 'lxml')
    company = soup.find_all('div', class_='companyCardWrapper')

    if not company:
        print(f"[page {page}] no company cards found (blocked, CAPTCHA, or end of pages)")
        consecutive_empty += 1
        if consecutive_empty >= MAX_CONSECUTIVE_EMPTY:
            print("Too many consecutive empty pages, stopping.")
            break
        time.sleep(5)
        continue

    consecutive_empty = 0  # reset on a successful page

    name, rating, reviews, jobs, industry, location = [], [], [], [], [], []

    for i in company:
        # 1. Name — guard against missing h2
        name_el = i.find('h2')
        name.append(name_el.text.strip() if name_el else None)

        # 2. Rating
        rating_el = i.find('span', class_='rating_text')
        rating.append(rating_el.text.strip() if rating_el else None)

        # 3. Reviews — match on href containing 'reviews', not just first ActionWrapper link
        rev_el = i.find('a', href=lambda h: h and 'reviews' in h.lower())
        reviews.append(rev_el.text.strip() if rev_el else None)

        # 4. Jobs
        job_el = i.find('a', href=lambda h: h and '-jobs-cmp' in h)
        jobs.append(job_el.text.strip() if job_el else None)

        # 5. Industry / location
        meta_el = i.find('span', class_='companyCardWrapper__interLinking')
        if meta_el and meta_el.text:
            meta_parts = [p.strip() for p in meta_el.text.split('|')]
            industry.append(meta_parts[0] if len(meta_parts) > 0 else None)
            location.append(meta_parts[1] if len(meta_parts) > 1 else None)
        else:
            industry.append(None)
            location.append(None)

    df = pd.DataFrame({
        'name': name,
        'rating': rating,
        'reviews': reviews,
        'jobs': jobs,
        'industry': industry,
        'location': location
    })
    df_list.append(df)
    print(f"[page {page}] scraped {len(df)} companies")

    # be polite — randomized delay to reduce block risk
    time.sleep(random.uniform(1.5, 3.0))

final = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()
final.to_csv('ambitionbox_companies.csv', index=False)
print(f"Done. Total rows: {len(final)}")

[page 1] scraped 20 companies
[page 2] scraped 20 companies
[page 3] scraped 20 companies
[page 4] scraped 20 companies
[page 5] scraped 20 companies
[page 6] scraped 20 companies
[page 7] scraped 20 companies
[page 8] scraped 20 companies
[page 9] scraped 20 companies
[page 10] scraped 20 companies
[page 11] scraped 20 companies
[page 12] scraped 20 companies
[page 13] scraped 20 companies
[page 14] scraped 20 companies
[page 15] scraped 20 companies
[page 16] scraped 20 companies
[page 17] scraped 20 companies
[page 18] scraped 20 companies
[page 19] scraped 20 companies
[page 20] scraped 20 companies
[page 21] scraped 20 companies
[page 22] scraped 20 companies
[page 23] scraped 20 companies
[page 24] scraped 20 companies
[page 25] scraped 20 companies
[page 26] scraped 20 companies
[page 27] scraped 20 companies
[page 28] scraped 20 companies
[page 29] scraped 20 companies
[page 30] scraped 20 companies
[page 31] scraped 20 companies
[page 32] scraped 20 companies
[page 33] scraped 20 companies
[page 34] scraped 20 companies
[page 35] scraped 20 companies
[page 36] scraped 20 companies
[page 37] scraped 20 companies
[page 38] scraped 20 companies
[page 39] scraped 20 companies
[page 40] scraped 20 companies
[page 41] scraped 20 companies
[page 42] scraped 20 companies
[page 43] scraped 20 companies
[page 44] scraped 20 companies
[page 45] scraped 20 companies
[page 46] scraped 20 companies
[page 47] scraped 20 companies
[page 48] scraped 20 companies
[page 49] scraped 20 companies
[page 50] scraped 20 companies
[page 51] scraped 20 companies
[page 52] scraped 20 companies
[page 53] scraped 20 companies
[page 54] scraped 20 companies
[page 55] scraped 20 companies
[page 56] scraped 20 companies
[page 57] scraped 20 companies
[page 58] scraped 20 companies
[page 59] scraped 20 companies
[page 60] scraped 20 companies
[page 61] scraped 20 companies
[page 62] scraped 20 companies
[page 63] scraped 20 companies
[page 64] scraped 20 companies
[page 65] scraped 20 companies
[page 66] scraped 20 companies
[page 67] scraped 20 companies
[page 68] scraped 20 companies
[page 69] scraped 20 companies
[page 70] scraped 20 companies
[page 71] scraped 20 companies
[page 72] scraped 20 companies
[page 73] scraped 20 companies
[page 74] scraped 20 companies
[page 75] scraped 20 companies
[page 76] scraped 20 companies
[page 77] scraped 20 companies
[page 78] scraped 20 companies
[page 79] scraped 20 companies
[page 80] scraped 20 companies
[page 81] scraped 20 companies
[page 82] scraped 20 companies
[page 83] scraped 20 companies
[page 84] scraped 20 companies
[page 85] scraped 20 companies
[page 86] scraped 20 companies
[page 87] scraped 20 companies
[page 88] scraped 20 companies
[page 89] scraped 20 companies
[page 90] scraped 20 companies
[page 91] scraped 20 companies
[page 92] scraped 20 companies
[page 93] scraped 20 companies
[page 94] scraped 20 companies
[page 95] scraped 20 companies
[page 96] scraped 20 companies
[page 97] scraped 20 companies
[page 98] scraped 20 companies
[page 99] scraped 20 companies
[page 100] scraped 20 companies
[page 101] scraped 20 companies
[page 102] scraped 20 companies
[page 103] scraped 20 companies
[page 104] scraped 20 companies
[page 105] scraped 20 companies
[page 106] scraped 20 companies
[page 107] scraped 20 companies
[page 108] scraped 20 companies
[page 109] scraped 20 companies
[page 110] scraped 20 companies
[page 111] scraped 20 companies
[page 112] scraped 20 companies
[page 113] scraped 20 companies
[page 114] scraped 20 companies
[page 115] scraped 20 companies
[page 116] scraped 20 companies
[page 117] scraped 20 companies
[page 118] scraped 20 companies
[page 119] scraped 20 companies
[page 120] scraped 20 companies
[page 121] scraped 20 companies
[page 122] scraped 20 companies
[page 123] scraped 20 companies
[page 124] scraped 20 companies
[page 125] scraped 20 companies
[page 126] scraped 20 companies
[page 127] scraped 20 companies
[page 128] scraped 20 companies
[page 129] scraped 20 companies
[page 130] scraped 20 companies
[page 131] scraped 20 companies
[page 132] scraped 20 companies
[page 133] scraped 20 companies
[page 134] scraped 20 companies
[page 135] scraped 20 companies
[page 136] scraped 20 companies
[page 137] scraped 20 companies
[page 138] scraped 20 companies
[page 139] scraped 20 companies
[page 140] scraped 20 companies
[page 141] scraped 20 companies
[page 142] scraped 20 companies
[page 143] scraped 20 companies
[page 144] scraped 20 companies
[page 145] scraped 20 companies
[page 146] scraped 20 companies
[page 147] scraped 20 companies
[page 148] scraped 20 companies
[page 149] scraped 20 companies
[page 150] scraped 20 companies
[page 151] scraped 20 companies
[page 152] scraped 20 companies
[page 153] scraped 20 companies
[page 154] scraped 20 companies
[page 155] scraped 20 companies
[page 156] scraped 20 companies
[page 157] scraped 20 companies
[page 158] scraped 20 companies
[page 159] scraped 20 companies
[page 160] scraped 20 companies
[page 161] scraped 20 companies
[page 162] scraped 20 companies
[page 163] scraped 20 companies
[page 164] scraped 20 companies
[page 165] scraped 20 companies
[page 166] scraped 20 companies
[page 167] scraped 20 companies
[page 168] scraped 20 companies
[page 169] scraped 20 companies
[page 170] scraped 20 companies
[page 171] scraped 20 companies
[page 172] scraped 20 companies
[page 173] scraped 20 companies
[page 174] scraped 20 companies
[page 175] scraped 20 companies
[page 176] scraped 20 companies
[page 177] scraped 20 companies
[page 178] scraped 20 companies
[page 179] scraped 20 companies
[page 180] scraped 20 companies
[page 181] scraped 20 companies
[page 182] scraped 20 companies
[page 183] scraped 20 companies
[page 184] scraped 20 companies
[page 185] scraped 20 companies
[page 186] scraped 20 companies
[page 187] scraped 20 companies
[page 188] scraped 20 companies
[page 189] scraped 20 companies
[page 190] scraped 20 companies
[page 191] scraped 20 companies
[page 192] scraped 20 companies
[page 193] scraped 20 companies
[page 194] scraped 20 companies
[page 195] scraped 20 companies
[page 196] scraped 20 companies
[page 197] scraped 20 companies
[page 198] scraped 20 companies
[page 199] scraped 20 companies
[page 200] scraped 20 companies
[page 201] scraped 20 companies
[page 202] scraped 20 companies
[page 203] scraped 20 companies
[page 204] scraped 20 companies
[page 205] scraped 20 companies
[page 206] scraped 20 companies
[page 207] scraped 20 companies
[page 208] scraped 20 companies
[page 209] scraped 20 companies
[page 210] scraped 20 companies
[page 211] scraped 20 companies
[page 212] scraped 20 companies
[page 213] scraped 20 companies
[page 214] scraped 20 companies
[page 215] scraped 20 companies
[page 216] scraped 20 companies
[page 217] scraped 20 companies
[page 218] scraped 20 companies
[page 219] scraped 20 companies
[page 220] scraped 20 companies
[page 221] scraped 20 companies
[page 222] scraped 20 companies
[page 223] scraped 20 companies
[page 224] scraped 20 companies
[page 225] scraped 20 companies
[page 226] scraped 20 companies
[page 227] scraped 20 companies
[page 228] scraped 20 companies
[page 229] scraped 20 companies
[page 230] scraped 20 companies
[page 231] scraped 20 companies
[page 232] scraped 20 companies
[page 233] scraped 20 companies
[page 234] scraped 20 companies
[page 235] scraped 20 companies
[page 236] scraped 20 companies
[page 237] scraped 20 companies
[page 238] scraped 20 companies
[page 239] scraped 20 companies
[page 240] scraped 20 companies
[page 241] scraped 20 companies
[page 242] scraped 20 companies
[page 243] scraped 20 companies
[page 244] scraped 20 companies
[page 245] scraped 20 companies
[page 246] scraped 20 companies
[page 247] scraped 20 companies
[page 248] scraped 20 companies
[page 249] scraped 20 companies
[page 250] scraped 20 companies
[page 251] scraped 20 companies
[page 252] scraped 20 companies
[page 253] scraped 20 companies
[page 254] scraped 20 companies
[page 255] scraped 20 companies
[page 256] scraped 20 companies
[page 257] scraped 20 companies
[page 258] scraped 20 companies
[page 259] scraped 20 companies
[page 260] scraped 20 companies
[page 261] scraped 20 companies
[page 262] scraped 20 companies
[page 263] scraped 20 companies
[page 264] scraped 20 companies
[page 265] scraped 20 companies
[page 266] scraped 20 companies
[page 267] scraped 20 companies
[page 268] scraped 20 companies
[page 269] scraped 20 companies
[page 270] scraped 20 companies
[page 271] scraped 20 companies
[page 272] scraped 20 companies
[page 273] scraped 20 companies
[page 274] scraped 20 companies
[page 275] scraped 20 companies
[page 276] scraped 20 companies
[page 277] scraped 20 companies
[page 278] scraped 20 companies
[page 279] scraped 20 companies
[page 280] scraped 20 companies
[page 281] scraped 20 companies
[page 282] scraped 20 companies
[page 283] scraped 20 companies
[page 284] scraped 20 companies
[page 285] scraped 20 companies
[page 286] scraped 20 companies
[page 287] scraped 20 companies
[page 288] scraped 20 companies
[page 289] scraped 20 companies
[page 290] scraped 20 companies
[page 291] scraped 20 companies
[page 292] scraped 20 companies
[page 293] scraped 20 companies
[page 294] scraped 20 companies
[page 295] scraped 20 companies
[page 296] scraped 20 companies
[page 297] scraped 20 companies
[page 298] scraped 20 companies
[page 299] scraped 20 companies
[page 300] scraped 20 companies
[page 301] scraped 20 companies
[page 302] scraped 20 companies
[page 303] scraped 20 companies
[page 304] scraped 20 companies
[page 305] scraped 20 companies
[page 306] scraped 20 companies
[page 307] scraped 20 companies
[page 308] scraped 20 companies
[page 309] scraped 20 companies
[page 310] scraped 20 companies
[page 311] scraped 20 companies
[page 312] scraped 20 companies
[page 313] scraped 20 companies
[page 314] scraped 20 companies
[page 315] scraped 20 companies
[page 316] scraped 20 companies
[page 317] scraped 20 companies
[page 318] scraped 20 companies
[page 319] scraped 20 companies
[page 320] scraped 20 companies
[page 321] scraped 20 companies
[page 322] scraped 20 companies
[page 323] scraped 20 companies
[page 324] scraped 20 companies
[page 325] scraped 20 companies
[page 326] scraped 20 companies
[page 327] scraped 20 companies
[page 328] scraped 20 companies
[page 329] scraped 20 companies
[page 330] scraped 20 companies
[page 331] scraped 20 companies
[page 332] scraped 20 companies
[page 333] scraped 20 companies
[page 334] scraped 20 companies
[page 335] scraped 20 companies
[page 336] scraped 20 companies
[page 337] scraped 20 companies
[page 338] scraped 20 companies
[page 339] scraped 20 companies
[page 340] scraped 20 companies
[page 341] scraped 20 companies
[page 342] scraped 20 companies
[page 343] scraped 20 companies
[page 344] scraped 20 companies
[page 345] scraped 20 companies
[page 346] scraped 20 companies
[page 347] scraped 20 companies
[page 348] scraped 20 companies
[page 349] scraped 20 companies
[page 350] scraped 20 companies
[page 351] scraped 20 companies
[page 352] scraped 20 companies
[page 353] scraped 20 companies
[page 354] scraped 20 companies
[page 355] scraped 20 companies
[page 356] scraped 20 companies
[page 357] scraped 20 companies
[page 358] scraped 20 companies
[page 359] scraped 20 companies
[page 360] scraped 20 companies
[page 361] scraped 20 companies
[page 362] scraped 20 companies
[page 363] scraped 20 companies
[page 364] scraped 20 companies
[page 365] scraped 20 companies
[page 366] scraped 20 companies
[page 367] scraped 20 companies
[page 368] scraped 20 companies
[page 369] scraped 20 companies
[page 370] scraped 20 companies
[page 371] scraped 20 companies
[page 372] scraped 20 companies
[page 373] scraped 20 companies
[page 374] scraped 20 companies
[page 375] scraped 20 companies
[page 376] scraped 20 companies
[page 377] scraped 20 companies
[page 378] scraped 20 companies
[page 379] scraped 20 companies
[page 380] scraped 20 companies
[page 381] scraped 20 companies
[page 382] scraped 20 companies
[page 383] scraped 20 companies
[page 384] scraped 20 companies
[page 385] scraped 20 companies
[page 386] scraped 20 companies
[page 387] scraped 20 companies
[page 388] scraped 20 companies
[page 389] scraped 20 companies
[page 390] scraped 20 companies
[page 391] scraped 20 companies
[page 392] scraped 20 companies
[page 393] scraped 20 companies
[page 394] scraped 20 companies
[page 395] scraped 20 companies
[page 396] scraped 20 companies
[page 397] scraped 20 companies
[page 398] scraped 20 companies
[page 399] scraped 20 companies
[page 400] scraped 20 companies
[page 401] scraped 20 companies
[page 402] scraped 20 companies
[page 403] scraped 20 companies
[page 404] scraped 20 companies
[page 405] scraped 20 companies
[page 406] scraped 20 companies
[page 407] scraped 20 companies
[page 408] scraped 20 companies
[page 409] scraped 20 companies
[page 410] scraped 20 companies
[page 411] scraped 20 companies
[page 412] scraped 20 companies
[page 413] scraped 20 companies
[page 414] scraped 20 companies
[page 415] scraped 20 companies
[page 416] scraped 20 companies
[page 417] scraped 20 companies
[page 418] scraped 20 companies
[page 419] scraped 20 companies
[page 420] scraped 20 companies
[page 421] scraped 20 companies
[page 422] scraped 20 companies
[page 423] scraped 20 companies
[page 424] scraped 20 companies
[page 425] scraped 20 companies
[page 426] scraped 20 companies
[page 427] scraped 20 companies
[page 428] scraped 20 companies
[page 429] scraped 20 companies
[page 430] scraped 20 companies
[page 431] scraped 20 companies
[page 432] scraped 20 companies
[page 433] scraped 20 companies
[page 434] scraped 20 companies
[page 435] scraped 20 companies
[page 436] scraped 20 companies
[page 437] scraped 20 companies
[page 438] scraped 20 companies
[page 439] scraped 20 companies
[page 440] scraped 20 companies
[page 441] scraped 20 companies
[page 442] scraped 20 companies
[page 443] scraped 20 companies
[page 444] scraped 20 companies
[page 445] scraped 20 companies
[page 446] scraped 20 companies
[page 447] scraped 20 companies
[page 448] scraped 20 companies
[page 449] scraped 20 companies
[page 450] scraped 20 companies
[page 451] scraped 20 companies
[page 452] scraped 20 companies
[page 453] scraped 20 companies
[page 454] scraped 20 companies
[page 455] scraped 20 companies
[page 456] scraped 20 companies
[page 457] scraped 20 companies
[page 458] scraped 20 companies
[page 459] scraped 20 companies
[page 460] scraped 20 companies
[page 461] scraped 20 companies
[page 462] scraped 20 companies
[page 463] scraped 20 companies
[page 464] scraped 20 companies
[page 465] scraped 20 companies
[page 466] scraped 20 companies
[page 467] scraped 20 companies
[page 468] scraped 20 companies
[page 469] scraped 20 companies
[page 470] scraped 20 companies
[page 471] scraped 20 companies
[page 472] scraped 20 companies
[page 473] scraped 20 companies
[page 474] scraped 20 companies
[page 475] scraped 20 companies
[page 476] scraped 20 companies
[page 477] scraped 20 companies
[page 478] scraped 20 companies
[page 479] scraped 20 companies
[page 480] scraped 20 companies
[page 481] scraped 20 companies
[page 482] scraped 20 companies
[page 483] scraped 20 companies
[page 484] scraped 20 companies
[page 485] scraped 20 companies
[page 486] scraped 20 companies
[page 487] scraped 20 companies
[page 488] scraped 20 companies
[page 489] scraped 20 companies
[page 490] scraped 20 companies
[page 491] scraped 20 companies
[page 492] scraped 20 companies
[page 493] scraped 20 companies
[page 494] scraped 20 companies
[page 495] scraped 20 companies
[page 496] scraped 20 companies
[page 497] scraped 20 companies
[page 498] scraped 20 companies
[page 499] scraped 20 companies
Done. Total rows: 9980

In [123]:
final

,name,rating,reviews,jobs,industry,location
0,TCS,None,1.2L Reviews,4.7k Jobs,IT Services & Consulting,Bengaluru +449 other locations
1,Accenture,None,75.4k Reviews,18.7k Jobs,IT Services & Consulting,Bengaluru +261 other locations
2,Wipro,None,66.6k Reviews,4.1k Jobs,IT Services & Consulting,Hyderabad +375 other locations
3,Cognizant,None,62.9k Reviews,900 Jobs,IT Services & Consulting,Hyderabad +234 other locations
4,Capgemini,None,55k Reviews,2k Jobs,IT Services & Consulting,Bengaluru +188 other locations
...,...,...,...,...,...,...
9975,Avant Garde Industries,None,114 Reviews,1 Jobs,Industrial Machinery,Mumbai +3 other locations
9976,State Bank of Mauritius,None,114 Reviews,-- Jobs,Banking,Mumbai +18 other locations
9977,Arya Iron & Steel Co.,None,114 Reviews,-- Jobs,Iron & Steel,Barbil +7 other locations
9978,Structwel,None,114 Reviews,-- Jobs,Engineering & Construction,Mumbai +10 other locations
9979,CIPACA,None,114 Reviews,-- Jobs,Chennai +13 other locations,NaN

In [124]:
final.to_csv('ambitionbox_companies.csv', index=False)